services: docker
script:
  - docker build -t meguca_test .
  - TRAVIS_JOB_ID="$TRAVIS_JOB_ID" TRAVIS_BRANCH="$TRAVIS_BRANCH" docker run -t --entrypoint scripts/docker_test.sh meguca_test
notifications:
  email:
    recipients:
      - scorpid33@gmail.com
    on_success: never
    on_failure: always
